schema: schema.graphql
documents: '**/*.graphql'
extensions:
  endpoints:
    Development:
      url: http://localhost:5454/api/graphql
      headers:
        Authorization: bearer ${CEBELCA_BIZ_API_KEY}
    Docker:
      url: http://localhost:8001/api/graphql
      headers:
        Authorization: bearer ${CEBELCA_BIZ_API_KEY}
    Production:
      url: https://cebelca-gateway.pinkstack.com/api/graphql
      headers:
        Authorization: bearer ${CEBELCA_BIZ_API_KEY}
