### Partners
GRAPHQL http://localhost:5454/api/graphql
Authorization: Bearer {{api_key}}

query {
    all_partners: partners {
        id
        ... on Partner {
            name
            city
        }
    }


#    eight_partner {
#        partner(value: "8") {
#            id
#        }
#    }
}

{
  "Authorization": "Bearer 12849495MWspScb4KmUZCEgNaOvFi0BAyfnokHVJ78tP3hze1j"
}