package biz.cebelca.gateway.schemagen

import biz.cebelca.gateway.CebelcaAPI
import biz.cebelca.gateway.graphql.GraphQLAPI
import zio.*
import zio.http.Client

object SchemaGen extends ZIOAppDefault:
  private def header(gitVersion: String): String =
    s"""# ─────────────────────────────────────────────────────────────────────────────
       |# AUTOGENERATED. DO NOT EDIT BY HAND!
       |#
       |# This GraphQL schema is rendered from the Scala schema definition in the
       |# `gateway` module. Any manual edit will be overwritten on the next generation.
       |#
       |# To regenerate: ./mill schema-gen.generate
       |#
       |# Generated from git: $gitVersion
       |# ─────────────────────────────────────────────────────────────────────────────
       |""".stripMargin

  private def program =
    for
      args      <- getArgs
      target     = args.headOption.getOrElse("schema.graphql")
      gitVersion = args.lift(1).getOrElse("unknown")
      sdl       <- CebelcaAPI.make.map(api => GraphQLAPI.make(api).render)
      _         <- ZIO.writeFile(target, s"${header(gitVersion)}\n$sdl")
      _         <- Console.printLine(s"Wrote GraphQL schema to $target (git: $gitVersion)")
    yield ()

  def run = program.provideSome[ZIOAppArgs](Client.default)
